version: "3"
services:
    coexya-azure-artifact-teams-publisher:
        container_name: coexya-azure-artifact-teams-publisher
        image: elyspio/azure-artifact-teams-publisher
        restart: always
        volumes:
            - "./config/front/conf.js:/back/wwwroot/conf.js"
            - "./config/back/appsettings.json:/back/appsettings.json"
        networks:
            - external
            - internal
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=external"
            - "traefik.http.middlewares.coexya-azure-artifact-teams-publisher-prefix.stripprefix.prefixes=/coexya/azure-artifact-teams-publisher"
            - "traefik.http.routers.coexya-azure-artifact-teams-publisher.middlewares=coexya-azure-artifact-teams-publisher-prefix@docker"
            - "traefik.http.routers.coexya-azure-artifact-teams-publisher.rule=PathPrefix(`/coexya/azure-artifact-teams-publisher`)"
            - "traefik.http.services.coexya-azure-artifact-teams-publisher.loadbalancer.server.port=4000"
            - "traefik.http.routers.coexya-azure-artifact-teams-publisher.entrypoints=external"



networks:
    internal:
        external: true
    external:
        external: true
